### ISSUE TITLE
ExtraBold & ExtraBoldItalic: Feature ccmp has not been defined

### ISSUE THREAD

**Issue by felipesanches** [MonicaRizzolli/Tomorrow#12]
This causes these two fonts to fail to be built.
![Screenshot at 2019-09-19 18:53:45](https://user-images.githubusercontent.com/213676/65284035-00cb2980-db28-11e9-9dd3-8800a20ad80a.png)

**Comment by felipesanches** [comment]
<img width="733" alt="Captura de Tela 2019-09-19 às 19 00 53" src="https://user-images.githubusercontent.com/213676/65284435-df5e4380-db0f-11e9-9f24-74244da5335c.png">

**Comment by felipesanches** [comment]
<img width="730" alt="Captura de Tela 2019-09-19 às 19 02 14" src="https://user-images.githubusercontent.com/213676/65284483-0583e380-db10-11e9-956c-d6bbd062f49c.png">

**Comment by felipesanches** [comment]
I suspect that this may be a fontmake bug actually. The disabled feature should have been ignored.

**Comment by felipesanches** [comment]
ok, I have fixed this by hitting the "update" button on the Features dialog in GlyphsApp.

This issue is now fixed. It will be closed once the code is merged at pull request #13

**Comment by MonicaRizzolli** [comment]
The code is now merged at pull request #13.
