### ISSUE TITLE
All fontfiles have bad usweightclass value (all are set to 400=Regular)

### ISSUE THREAD

**Issue by felipesanches** [MonicaRizzolli/Tomorrow#14]
here's an example:
![Screenshot at 2019-09-19 20:10:03](https://user-images.githubusercontent.com/213676/65287413-b0a59480-db32-11e9-9832-ccec741f6a14.png)

**Comment by felipesanches** [comment]
I have been trying to fix this, but it is unclear exactly how should I do it.

I asked GlyphsApp (most likely @schriftgestalt) on twitter:
https://twitter.com/juca_gnu/status/1174830802804383747

**Comment by felipesanches** [comment]
@schriftgestalt, what are the differences and side effets of each of these on the Instances tab? (1) weight dropdown (2) axes coordinates - Weight (3) weightClass custom param. And also (4) Axes Coordinates - weight on the Masters tab.

**Comment by felipesanches** [comment]
@anthrotype, I changed all of those and fontmake still outputs TTFs with OS/2 usweightclass = 400... Maybe a bug in fontmake?

**Comment by davelab6** [comment]
I suggest to post screenshots on the forum.glyphsapp.com because GS isn't
the only person in the world who can solve this for you.

**Comment by felipesanches** [comment]
sure ;-)

**Comment by felipesanches** [comment]
I think I will spend some time now investigating how fontmake handles this. I may send them a PR.

**Comment by schriftgestalt** [comment]
The only place where to get reliable weight/widthClass values are the settings in the instances. Either the properties directly or the custom parameter (the later overwrites the former).

**Comment by felipesanches** [comment]
thanks, @schriftgestalt !

**Comment by anthrotype** [comment]
when building from `-g` glyphs sources you need to pass the `-i` option to fontmake, otherwise it only builds the masters and the instance custom parameters won't be applied otherwise
